### ISSUE TITLE
TODO list (in russian)

### ISSUE THREAD

**Issue by IlyaKachan** [IlyaKachan/thesis#5]
### Глава про асимптотические разложения
- [x] теорема 3.1 (существование решений) - добавить ссылку на Ноенкирха (и заменить пространство на C^2_b)
- [x] теоремы 3.3, 3.4 (непрерывная зависимость решений) - объединить в одну с двумя утверждениями.
- [x] с. 81 (доказательство асимптотических разложений) - в верхних индексах вида `( | )` заменить `|` на `;` + пояснить словами.
- [x] коммутативный случай - привести в соответствие с книгой

### Глава про методы интегрирования
- [x] с. 108 (переход к уравнению Стратоновича) - вынести 3 интеграла (прямой, обратный, симметрический) в предварительные сведения
- [x] с. 112 (дифф. уравнения для мат. ожиданий и плотностей решений) - перенести интеграл Вика в предварительные сведения
- [x] теорема 4.4 (дифф. уравнение для плотности) - уточнить понятие "достаточно гладкие и ограниченные"
- [x] добавить пример по устойчивости линейного однородного уравнения через явную формулу.

### Глава про устойчивость в конечномерных и гильбертовых пространствах
- [x] раздел 2.1 (конечномерные) - убрать запаздывание
- [x] формула (2.2) (выпуклые множества для f, g) - поправить определение решения (на бета-слабое решение). Пояснение про существование решений оформить со ссылкой на книгу.
- [x] теоремы 2.1, 2.2 (общие теоремы об устойчивости конечномерных по Ляпунову) - сделать сноску об авторстве Ярослава со ссылкой на новую статью
- [x] убрать 3-й уровень нумерации 2.1.1, 2.1.2
- [x] посмотреть работы, ссылающиеся на статью Лю - нет ли там нашей теоремы !!!
- [x] раздел 2.2 (бесконечномерные) - убрать омега и запаздывание
- [x] теорема 2.4 (основная для бесконечномерных) - изменить описание теоремы на притяжение к нулю (это не асимптотическая устойчивость в смысле Ляпунова)
- [x] пример 2.2 (бесконечномерные) - подсократить длинные формулы
- [x] перенести всю главу в конец диссертации (возможно)

### Предварительные сведения
- [x] раздел "теория меры" - ввести интеграл Бохнера вместо интеграла Лебега
- [x] раздел "теория полугрупп" - добавить 2 примера: для параболических уравнений и для матриц
- [ ] раздел "теория случайных процессов" - не нужен. Вместо него 2 раздела: стохастическое интегрирование в гильбертовом пространстве и стохастическое интегрирование по дробному броуновскому

### Введение
- [x] пересмотреть, не пропущены ли важные источники 
- [x] сделать акцент на структуру "обзор источников + мотивация".
